// Loading the game code from the code cache (see loader.h).
#include "loader.h"

#include <llvm/ExecutionEngine/JITLink/EHFrameSupport.h>
#include <llvm/ExecutionEngine/Orc/AbsoluteSymbols.h>
#include <llvm/ExecutionEngine/Orc/EHFrameRegistrationPlugin.h>
#include <llvm/ExecutionEngine/Orc/LLJIT.h>
#include <llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h>
#include <llvm/Support/MemoryBuffer.h>
#include <llvm/Support/TargetSelect.h>

#include <algorithm>
#include <dirent.h>
#include <dlfcn.h>
#include <sys/stat.h>
#include <unistd.h>

#include <array>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <mutex>
#include <unordered_map>
#include <utility>
#include <vector>

#include "../crash_info.h"
#include "../disc/crypto.h"
#include "../release.h"
#include "compile.h"
#include "emit.h"
#include "program.h"
#include "recomp_table.h"
#include "recomp_version.h"  // generated by CMakeLists.txt

void log_msg(const char* fmt, ...) __attribute__((format(printf, 1, 2)));

// the tables of recomp_table.h, filled by load_game_code (no build/gen in this build)
extern "C" {
const RecompEntry* g_recomp_funcs = nullptr;
unsigned g_recomp_func_count = 0;
const RecompImport* g_recomp_imports = nullptr;
unsigned g_recomp_import_count = 0;
uint32_t g_recomp_entry_point = recomp::kSupportedEntryPoint;

void hle_unimplemented(Cpu* c, const char* lib, const char* name);
extern const char wwhd_hooks[], wwhd_hooks_end[];  // recomp_data.S: the hook lists the code was compiled with

// runtime_stubs.cpp (generated by CMake): the game functions the runtime calls directly
// (f_X, f_X_orig) are stubs that jump through these slots
extern PpcFunc wwhd_jit_slots[];
extern const char* const wwhd_jit_names[];
extern const unsigned wwhd_jit_count;
}

namespace recomp {
namespace {

// imported functions without an HLE implementation: one stub each, so the log can name them
constexpr size_t kStubs = 1024;
const char* g_stub_lib[kStubs];
const char* g_stub_name[kStubs];
template <size_t I>
void unimplemented_stub(Cpu* c) { hle_unimplemented(c, g_stub_lib[I], g_stub_name[I]); }
template <size_t... I>
constexpr std::array<PpcFunc, kStubs> make_stubs(std::index_sequence<I...>) { return {&unimplemented_stub<I>...}; }
constexpr std::array<PpcFunc, kStubs> g_stubs = make_stubs(std::make_index_sequence<kStubs>());

// what the game code links against: libwwhd's exported symbols (runtime, HLE, hooks), and for
// imports without HLE an unimplemented stub
struct Resolver {
    void* self = nullptr;
    std::unordered_map<std::string, std::pair<std::string, std::string>> imports;  // imp_* -> (lib, name)
    std::unordered_map<std::string, void*> stubbed;
    size_t stubs = 0;
    std::mutex m;

    void* resolve(const std::string& sym) {
        if (void* p = dlsym(self, sym.c_str())) return p;
        auto it = imports.find(sym);
        if (it == imports.end()) return nullptr;
        std::lock_guard<std::mutex> lk(m);
        void*& s = stubbed[sym];
        if (!s && stubs < kStubs) {
            g_stub_lib[stubs] = it->second.first.c_str();
            g_stub_name[stubs] = it->second.second.c_str();
            s = (void*)g_stubs[stubs++];
        }
        return s;
    }
};

class SelfGenerator : public llvm::orc::DefinitionGenerator {
public:
    explicit SelfGenerator(Resolver& r) : r_(r) {}
    llvm::Error tryToGenerate(llvm::orc::LookupState&, llvm::orc::LookupKind, llvm::orc::JITDylib& jd,
                              llvm::orc::JITDylibLookupFlags, const llvm::orc::SymbolLookupSet& syms) override {
        llvm::orc::SymbolMap found;
        for (auto& [name, flags] : syms)
            if (void* p = r_.resolve((*name).str()))
                found[name] = {llvm::orc::ExecutorAddr::fromPtr(p), llvm::JITSymbolFlags::Exported | llvm::JITSymbolFlags::Callable};
        if (found.empty()) return llvm::Error::success();
        return jd.define(llvm::orc::absoluteSymbols(std::move(found)));
    }

private:
    Resolver& r_;
};

std::string read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    return std::string(std::istreambuf_iterator<char>(f), {});
}

bool write_file(const std::string& path, const std::string& s) {
    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    f << s;
    return f.good();
}

std::string hex(const uint8_t* p, size_t n) {
    std::string s;
    char b[3];
    for (size_t i = 0; i < n; i++) snprintf(b, sizeof b, "%02x", p[i]), s += b;
    return s;
}

constexpr const char* kComplete = "/complete";  // key of the finished cache
constexpr const char* kBuilding = "/building";  // key of the compile in progress

}  // namespace

std::string code_cache_key(const std::string& rpxPath) {
    std::string rpx = read_file(rpxPath);
    if (rpx.empty()) return "";
    uint8_t h[20], hk[20];
    disc::sha1((const uint8_t*)rpx.data(), rpx.size(), h);
    disc::sha1((const uint8_t*)wwhd_hooks, (size_t)(wwhd_hooks_end - wwhd_hooks), hk);
    std::string key = std::string("recompiler ") + WWHD_RECOMP_VERSION + "\nhooks " + hex(hk, 20) + "\nrpx " + hex(h, 20) + "\ncpu " +
                      host_features() + "\nopt " + std::to_string(kDefaultOptLevel) + "\n";
    // another release: its address map decides the function names
    uint32_t entry = rpx.size() >= 0x1C ? (uint8_t)rpx[0x18] << 24 | (uint8_t)rpx[0x19] << 16 | (uint8_t)rpx[0x1A] << 8 | (uint8_t)rpx[0x1B] : 0;
    if (release::known_entry(entry) && entry != kSupportedEntryPoint) {
        std::string map = release::map_text(entry);
        uint8_t hm[20];
        disc::sha1((const uint8_t*)map.data(), map.size(), hm);
        key += "map " + hex(hm, 20) + "\n";
    }
    return key;
}

bool code_cache_ready(const std::string& dir, const std::string& key) {
    return !key.empty() && read_file(dir + kComplete) == key;
}

bool begin_code_cache(const std::string& dir, const std::string& key) {
    mkdir(dir.c_str(), 0700);
    if (read_file(dir + kBuilding) == key) return true;
    if (DIR* d = opendir(dir.c_str())) {
        while (dirent* e = readdir(d))
            if (e->d_name[0] != '.') unlink((dir + "/" + e->d_name).c_str());
        closedir(d);
    }
    write_file(dir + kBuilding, key);
    return false;
}

bool finish_code_cache(const std::string& dir, const std::string& key, std::string& err) {
    if (!write_file(dir + kComplete, key)) {
        err = "cannot write " + dir + kComplete;
        return false;
    }
    unlink((dir + kBuilding).c_str());
    return true;
}

bool load_game_code(const std::string& rpxPath, const std::string& dir, std::string& err) {
    auto t0 = std::chrono::steady_clock::now();
    auto ms = [&] { return (long)std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - t0).count(); };
    static Program prog;  // the tables point into it
    if (!prog.load(rpxPath, err)) return false;
    if (!release::select(prog.entry)) {
        err = rpxPath + " is not a supported game version";
        return false;
    }
    log_msg("[recomp] game release: %s", release::name());
    crash_info::set("code", std::string("compiled on the device: recompiler ") + WWHD_RECOMP_VERSION + ", -O" +
                                std::to_string(kDefaultOptLevel) + ", CPU features " + host_features());
    long tAnalyze = ms();

    static Resolver res;
    Dl_info info;
    if (!dladdr((void*)&load_game_code, &info) || !(res.self = dlopen(info.dli_fname, RTLD_NOW | RTLD_NOLOAD))) {
        err = "cannot find the runtime library";
        return false;
    }
    for (auto& [slot, im] : prog.imports)
        if (im.function) res.imports[import_symbol(im)] = {im.lib, im.name};

    LLVMInitializeAArch64TargetInfo();
    LLVMInitializeAArch64Target();
    LLVMInitializeAArch64TargetMC();
    auto jit = llvm::orc::LLJITBuilder()
                   .setJITTargetMachineBuilder(llvm::orc::JITTargetMachineBuilder(llvm::Triple("aarch64-unknown-linux-android30")))
                   .setPlatformSetUp(llvm::orc::setUpInactivePlatform)
                   .setObjectLinkingLayerCreator([](llvm::orc::ExecutionSession& es, const llvm::Triple&)
                                                     -> llvm::Expected<std::unique_ptr<llvm::orc::ObjectLayer>> {
                       auto ol = std::make_unique<llvm::orc::ObjectLinkingLayer>(es);
                       // the code's unwind tables (compile.cpp), for backtraces in crash logs
                       ol->addPlugin(std::make_unique<llvm::orc::EHFrameRegistrationPlugin>(
                           es, std::make_unique<llvm::jitlink::InProcessEHFrameRegistrar>()));
                       return ol;
                   })
                   .create();
    if (!jit) {
        err = "JIT: " + llvm::toString(jit.takeError());
        return false;
    }
    static std::unique_ptr<llvm::orc::LLJIT> keep;  // the code lives as long as the process
    keep = std::move(*jit);
    llvm::orc::JITDylib& jd = keep->getMainJITDylib();
    jd.addGenerator(std::make_unique<SelfGenerator>(res));

    size_t objects = 0;
    for (;; objects++) {
        char name[32];
        snprintf(name, sizeof name, "/code_%03zu.o", objects);
        auto buf = llvm::MemoryBuffer::getFile(dir + name);
        if (!buf) break;
        if (auto e = keep->addObjectFile(std::move(*buf))) {
            err = std::string(name + 1) + ": " + llvm::toString(std::move(e));
            return false;
        }
    }
    if (!objects) {
        err = "no compiled code in " + dir;
        return false;
    }

    // one lookup links everything; the game functions, then the runtime's direct references
    llvm::orc::ExecutionSession& es = keep->getExecutionSession();
    llvm::orc::SymbolLookupSet want;
    std::vector<llvm::orc::SymbolStringPtr> names;
    char buf[32];
    for (uint32_t a : prog.entries) {  // named by their USA address (emit.cpp, sym)
        uint32_t u = release::usa_code(a);
        snprintf(buf, sizeof buf, u ? "f_%08X" : "f_E%08X", u ? u : a);
        names.push_back(es.intern(buf));
    }
    for (unsigned i = 0; i < wwhd_jit_count; i++) names.push_back(es.intern(wwhd_jit_names[i]));
    for (auto& n : names) want.add(n);
    auto syms = es.lookup(llvm::orc::makeJITDylibSearchOrder(&jd), std::move(want));
    if (!syms) {
        err = "linking: " + llvm::toString(syms.takeError());
        return false;
    }
    auto addr = [&](size_t i) { return (*syms)[names[i]].getAddress().toPtr<PpcFunc>(); };

    static std::vector<RecompEntry> funcs;
    funcs.clear();
    for (size_t i = 0; i < prog.entries.size(); i++) funcs.push_back({prog.entries[i], addr(i)});
    for (unsigned i = 0; i < wwhd_jit_count; i++) wwhd_jit_slots[i] = addr(prog.entries.size() + i);

    static std::vector<RecompImport> imports;
    imports.clear();
    for (auto& [slot, im] : prog.imports) {
        PpcFunc fn = im.function ? (PpcFunc)res.resolve(import_symbol(im)) : nullptr;
        if (im.function && !fn) {
            err = "too many unimplemented imports";
            return false;
        }
        imports.push_back({slot, im.function ? slot : im.dataAddr, im.lib.c_str(), im.name.c_str(), im.function, fn});
    }
    // profiling aid: WWHD_PERF_MAP=path writes "host address, size, name" of every game function
    // (perf map format) for symbolizing samples in the JIT-linked code (simpleperf shows it as unknown)
    if (const char* pm = getenv("WWHD_PERF_MAP")) {
        std::vector<std::pair<uintptr_t, uint32_t>> v;
        for (auto& f : funcs) v.push_back({(uintptr_t)f.fn, release::usa_code(f.addr) ? release::usa_code(f.addr) : f.addr});
        std::sort(v.begin(), v.end());
        if (FILE* f = fopen(pm, "w")) {
            for (size_t i = 0; i < v.size(); i++) {
                size_t size = i + 1 < v.size() ? v[i + 1].first - v[i].first : 4096;
                fprintf(f, "%lx %zx f_%08X\n", (unsigned long)v[i].first, size, v[i].second);
            }
            fclose(f);
        }
    }
    g_recomp_funcs = funcs.data();
    g_recomp_func_count = (unsigned)funcs.size();
    g_recomp_imports = imports.data();
    g_recomp_import_count = (unsigned)imports.size();
    g_recomp_entry_point = prog.entry;
    log_msg("[recomp] loaded %zu objects: %zu functions, %zu imports (%zu unimplemented); analysis %ld ms, total %ld ms", objects,
            funcs.size(), imports.size(), res.stubs, tAnalyze, ms());
    return true;
}

}  // namespace recomp
